-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 21:02:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`checkout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`checkout` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`checkout` (
  `id` INT NOT NULL,
  `checkouttime` DATETIME NULL,
  `checkintime` DATETIME NULL,
  `duedate` DATETIME NULL,
  `equipment_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `equipment_checkout_id`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `mydb`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_ckechout_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `id_idx` ON `mydb`.`checkout` (`equipment_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `uid_idx` ON `mydb`.`checkout` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id` INT NOT NULL,
  `barcode` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `barcode_UNIQUE` ON `mydb`.`equipment` (`barcode` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`equipment` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`request` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `description` LONGTEXT NULL,
  `accepted` TINYINT NULL,
  `user_id` INT NULL,
  `equipment_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `equipment_request_id`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `mydb`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_request_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`request` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `eid_idx` ON `mydb`.`request` (`equipment_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `uid_idx` ON `mydb`.`request` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uid` INT NOT NULL,
  `isfaculty` TINYINT NULL,
  PRIMARY KEY (`uid`));

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
